In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from sklearn.cluster import SpectralClustering
from sklearn import metrics
dataset = fetch_20newsgroups(subset='all', shuffle=True, download_if_missing=True)

np.random.seed(123)
texts = dataset.data # Extract text
target = dataset.target # Extract target
texts[0:10]
target[0:10]

array([10,  3, 17,  3,  4, 12,  4, 10, 10, 19])

In [ ]:
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(texts)

In [ ]:
print(f'{X.shape[0]}, {X.shape[1]}')
X[0:10, 0:10].todense()

18846, 173451


matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.15763399, 0.    

In [ ]:
    solution = SpectralClustering(n_clusters=20, assign_labels='kmeans').fit(X)
    type(solution)

sklearn.cluster._spectral.SpectralClustering

In [ ]:
print(f'{solution.labels_[0:20]}\n{target[0:20]}')
metrics.adjusted_rand_score(solution.labels_, target)

[ 8  0  9 16 13  1 13  8  8 13 11 15 13 13 13 13 13 13  4  1]
[10  3 17  3  4 12  4 10 10 19 19 11 19 13  0 17 12 12 11  8]


0.06820715915878511